/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A snapshot (CoW fork) of a workspace with isolated read/write operations. */
export declare class SnapshotWorkspace {
  /** Check whether a virtual path exists in this snapshot. */
  exists(path: string): Promise<boolean>
  /** Get metadata for a virtual path in this snapshot. */
  stat(path: string): Promise<StatResult>
  /** Read the raw bytes of a file at the given virtual path in this snapshot. */
  readBytes(path: string): Promise<Buffer>
  /**
   * Write content to a file in this snapshot (copy-on-write).
   *
   * @param path - Virtual path to write to.
   * @param content - Raw bytes to write.
   */
  write(path: string, content: Buffer): Promise<void>
  /** Export the source-to-virtual (or reverse) path mapping for this snapshot. */
  exportMapping(reverse?: boolean | undefined | null, relativeTo?: string | undefined | null): Promise<Record<string, string>>
  /** Destroy this snapshot, removing all its files from disk. */
  destroy(): Promise<void>
}
export type JsSnapshotWorkspace = SnapshotWorkspace

export declare class Workspace {
  /**
   * Initialize a new workspace at the given path.
   *
   * @param path - Root directory for the workspace.
   * @param strategy - Materialization strategy: "reflink" (default), "symlink", "hardlink", or "virtual".
   */
  static init(path: string, strategy?: string | undefined | null): Workspace
  /**
   * Open an existing workspace.
   *
   * @param path - Root directory of an existing workspace.
   */
  static open(path: string): Workspace
  /**
   * Map a source directory to a virtual mount point.
   *
   * @param source - Source directory path on disk.
   * @param mount - Virtual mount point (e.g. "/docs").
   * @returns Summary of the mapping operation.
   */
  map(source: string, mount: string): Promise<MapSummary>
  /**
   * Remove a mapping at the given mount point.
   *
   * @param mount - Virtual mount point to unmap.
   * @returns Summary with entries_removed count.
   */
  unmap(mount: string): Promise<UnmapSummary>
  /** Move a virtual entry from one path to another. */
  mv(from: string, to: string): Promise<void>
  /** Copy a virtual entry from one path to another. */
  cp(from: string, to: string): Promise<void>
  /** Create a virtual directory. */
  mkdir(path: string): Promise<void>
  /**
   * Remove a virtual directory.
   *
   * @param path - Virtual path to remove.
   * @param recursive - If true, remove all children recursively.
   */
  rmdir(path: string, recursive: boolean): Promise<void>
  /** Rename a virtual entry (last path component only). */
  rename(path: string, newName: string): Promise<void>
  /** Check whether a virtual path exists. */
  exists(path: string): Promise<boolean>
  /** Get metadata for a virtual path. */
  stat(path: string): Promise<StatResult>
  /** Read the raw bytes of a file at the given virtual path. */
  readBytes(path: string): Promise<Buffer>
  /** Refresh the workspace by detecting source changes. */
  refresh(): Promise<RefreshSummary>
  /** Get workspace status summary. */
  status(): Promise<StatusResult>
  /**
   * Export the source-to-virtual (or reverse) path mapping.
   *
   * @param reverse - If true, export virtual-to-source mapping.
   * @param relativeTo - Base path for relativizing source paths.
   */
  exportMapping(reverse?: boolean | undefined | null, relativeTo?: string | undefined | null): Promise<Record<string, string>>
  /**
   * Map multiple source directories in a single batch.
   *
   * @param mappings - Array of [sourcePath, mountPoint] tuples.
   */
  mapBatch(mappings: Array<Array<string>>): Promise<BatchMapSummary>
  /**
   * Match virtual paths against a glob pattern.
   *
   * @param pattern - Glob pattern (e.g. "/docs/*.txt", "/docs/**\/*.md").
   */
  rglob(pattern: string): Promise<Array<string>>
  /**
   * Refresh the workspace with optional SHA-256 hash verification.
   *
   * When `verifyHashes` is true, files whose mtime/size are unchanged
   * are additionally verified via SHA-256 to detect silent modifications.
   *
   * @param verifyHashes - Enable hash-based change detection.
   */
  refreshWithHashVerification(verifyHashes: boolean): Promise<RefreshSummary>
  /** List all snapshot names. */
  listSnapshots(): Promise<Array<string>>
  /** Destroy a named snapshot. */
  destroySnapshot(name: string): Promise<void>
  /**
   * Create a named snapshot (CoW fork) of the current workspace.
   *
   * @param name - Snapshot name (used as subdirectory name).
   * @returns A SnapshotWorkspace handle for the new snapshot.
   */
  snapshot(name: string): Promise<JsSnapshotWorkspace>
  /**
   * Open an existing named snapshot.
   *
   * @param name - Snapshot name to open.
   * @returns A SnapshotWorkspace handle.
   */
  openSnapshot(name: string): Promise<JsSnapshotWorkspace>
}
export type JsWorkspace = Workspace

export interface BatchMapSummary {
  entriesAdded: number
  reflinked: number
  copied: number
  symlinked: number
  hardlinked: number
  dirsCreated: number
  errors: Array<Array<string>>
}

export interface MapSummary {
  entriesAdded: number
  reflinked: number
  copied: number
  symlinked: number
  hardlinked: number
  dirsCreated: number
  errors: number
}

export interface RefreshSummary {
  added: number
  refreshed: number
  removed: number
  errors: number
}

export interface StatResult {
  virtualPath: string
  sourcePath: string
  sizeBytes: number
  mtimeNs: number
  entryType: string
  materialized: boolean
}

export interface StatusResult {
  totalEntries: number
  sourceRoots: number
  materializedRoot: string
  lastUpdatedEpochSecs: number
}

export interface UnmapSummary {
  entriesRemoved: number
}
